version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"


